//Error
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";

//Weather
export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED"

//Drone
export const FETCH_DRONE = "API_CALL_REQUEST";
export const DRONE_DATA_RECEIVED = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

//Map
export const MAP_CALL_REQUEST = "MAP_CALL_REQUEST";
export const MAP_CALL_SUCCESS = "MAP_CALL_SUCCESS";
export const MAP_CALL_FAILURE = "MAP_CALL_FAILURE";